const express = require('express')
const productController = require('../controller/productController')
const cartController = require('../controller/cartController')
const wishlistController = require('../controller/wishlistController')
const verifyToken = require('../middleware/userAuth')
const usrRouter = express.Router()

usrRouter.post('/prdcts', (productController.prdcts))
    .get('/category/:category', (productController.getProductByCategory))
    .get('/prdcts/:id', (productController.getProductById))
    .get('/products', (productController.getAllProducts))
    .use(verifyToken)
    .post('/cart/:id', verifyToken, (cartController.addProductToCart))
    .get('/cart/:id', (cartController.getCartProduct))
    .delete('/cart/:id', (cartController.deleteProductCart))
    // .patch('/cart/:userId', (cartController.updateQuantity))
    .post('/wishlist/:id', (wishlistController.addProductToWishList))
    .get('/wishlist/:id', (wishlistController.getWishlistProduct))
    .post('/payment/:id', (productController.payment))
    .post('/confirm-payment', (productController.confirmPayment))
    .delete('/wishlist/:userId', (wishlistController.deleteProductWishlist))
    .post('/payment', (productController.singlePayment))
    .post('/product/confirm-payment', (productController.productConfirmPayment))

module.exports = usrRouter